//! Core run types: [`WorldRun`], [`RunState`], [`RunResult`].

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::end_condition::EndCondition;

/// Stable identifier for a faction (human player guild or AI sub-faction).
pub type FactionId = String;

/// Stable identifier for a single world run epoch.
pub type RunId = Uuid;

// ─── WorldRun ────────────────────────────────────────────────────────────────

/// A single competitive world epoch.
///
/// Both human player factions and the Synthesis AI civilisation compete
/// inside one `WorldRun`.  When the `end_condition` is satisfied (or the
/// run duration expires), the run ends and a new world is generated.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldRun {
    /// Unique stable identifier.
    pub id: RunId,

    /// Current lifecycle state.
    pub state: RunState,

    /// World tick at which this run started.
    pub start_tick: u64,

    /// World tick at which this run ended (None while active).
    pub end_tick: Option<u64>,

    /// Condition that ends this run.
    pub end_condition: EndCondition,

    /// Human player faction IDs competing in this run.
    pub player_factions: Vec<FactionId>,

    /// Synthesis AI faction IDs active in this run.
    pub ai_factions: Vec<FactionId>,

    /// Optional world seed passed to WAC for this run's world generation.
    pub world_seed: u64,

    /// Human-readable run label (e.g. "Season 3 — Crystal Wastes").
    pub label: String,
}

impl WorldRun {
    /// Create a new run in `Pending` state.
    pub fn new(
        end_condition:   EndCondition,
        player_factions: Vec<FactionId>,
        ai_factions:     Vec<FactionId>,
        world_seed:      u64,
        label:           impl Into<String>,
    ) -> Self {
        Self {
            id:              Uuid::new_v4(),
            state:           RunState::Pending,
            start_tick:      0,
            end_tick:        None,
            end_condition,
            player_factions,
            ai_factions,
            world_seed,
            label:           label.into(),
        }
    }

    /// Begin the run at the given tick.
    pub fn start(&mut self, tick: u64) {
        self.state      = RunState::Active;
        self.start_tick = tick;
    }

    /// End the run with a result.
    pub fn end(&mut self, tick: u64, result: RunResult) {
        self.state    = RunState::Ended(result);
        self.end_tick = Some(tick);
    }

    /// True if the run is currently in progress.
    pub fn is_active(&self) -> bool {
        matches!(self.state, RunState::Active)
    }
}

// ─── RunState ────────────────────────────────────────────────────────────────

/// Lifecycle state of a [`WorldRun`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RunState {
    /// Created but not yet started.
    Pending,
    /// Actively running — factions compete.
    Active,
    /// Run has ended; contains the outcome.
    Ended(RunResult),
}

// ─── RunResult ───────────────────────────────────────────────────────────────

/// The outcome of a completed [`WorldRun`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RunResult {
    /// The winning faction (None = draw / time-out).
    pub winner: Option<FactionId>,

    /// The losing factions (multiple in case of draw).
    pub losers: Vec<FactionId>,

    /// Which [`EndCondition`] triggered the end.
    pub condition_triggered: EndCondition,

    /// Optional narrative summary generated by the WorldDirector.
    pub summary: Option<String>,

    /// Winner meta rewards to persist.
    pub winner_rewards: Vec<crate::meta::RunReward>,

    /// Loser penalties to apply.
    pub loser_penalties: Vec<crate::meta::SkillDecay>,
}

impl RunResult {
    pub fn winner(
        winner:    FactionId,
        losers:    Vec<FactionId>,
        condition: EndCondition,
    ) -> Self {
        Self {
            winner:               Some(winner),
            losers,
            condition_triggered:  condition,
            summary:              None,
            winner_rewards:       vec![],
            loser_penalties:      vec![],
        }
    }

    pub fn draw(condition: EndCondition, all_factions: Vec<FactionId>) -> Self {
        Self {
            winner:              None,
            losers:              all_factions,
            condition_triggered: condition,
            summary:             None,
            winner_rewards:      vec![],
            loser_penalties:     vec![],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::end_condition::EndCondition;

    fn make_run() -> WorldRun {
        WorldRun::new(
            EndCondition::SurvivalUntilTick(1000),
            vec!["humans".into()],
            vec!["synthesis".into()],
            42,
            "Test Run",
        )
    }

    #[test]
    fn run_starts_pending() {
        let r = make_run();
        assert!(matches!(r.state, RunState::Pending));
    }

    #[test]
    fn run_transitions_to_active() {
        let mut r = make_run();
        r.start(0);
        assert!(r.is_active());
    }

    #[test]
    fn run_ends_with_result() {
        let mut r = make_run();
        r.start(0);
        r.end(500, RunResult::draw(EndCondition::SurvivalUntilTick(1000), vec![]));
        assert!(matches!(r.state, RunState::Ended(_)));
        assert_eq!(r.end_tick, Some(500));
    }
}
