//! [`WorldDirector`] — faction balance, biome pressure, and world events.
//!
//! The WorldDirector sits above all factions and enforces global stability:
//!
//! ```text
//! WorldDirector
//!   ├─ prevents KI snowball (AI getting too dominant)
//!   ├─ prevents player stagnation  
//!   ├─ generates zone conflicts
//!   ├─ regulates resource scarcity
//!   └─ triggers world events (disasters, bonuses, biome mutations)
//! ```
//!
//! > "Verhindert KI snowball, erzeugt Konflikte in Zonen, reguliert resource scarcity"
//! > — `docs/WORLD.md`

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

use crate::zone::{FactionId, Zone, ZoneId, ZoneState};

// ─── PressureField ───────────────────────────────────────────────────────────

/// Biome pressure map across all zones.
///
/// High pressure in a zone triggers biome evolution (terrain corruption,
/// resource mutation, AI adaptation).  Updated from combat intensity and
/// economy imbalance.
pub type PressureField = BTreeMap<ZoneId, f32>;

// ─── BalanceMatrix ───────────────────────────────────────────────────────────

/// Cross-faction balance state.
///
/// The director uses this to detect runaway dominance and apply corrective
/// pressure.
pub type BalanceMatrix = BTreeMap<FactionId, f32>;

// ─── WorldDirector ───────────────────────────────────────────────────────────

/// Orchestrates world-level balance and biome evolution.
#[derive(Debug, Default)]
pub struct WorldDirector {
    /// Biome pressure per zone — drives terrain evolution.
    pub biome_pressure_map: PressureField,

    /// Balance score per faction (1.0 = dominant, 0.0 = eliminated).
    pub faction_balance:    BalanceMatrix,

    /// Macro-level economic stability (0.0 = collapse, 1.0 = stable).
    pub economic_stability: f32,

    /// World events active this tick.
    pub active_events: Vec<WorldEvent>,
}

impl WorldDirector {
    pub fn new() -> Self {
        Self {
            economic_stability: 1.0,
            ..Default::default()
        }
    }

    /// Run one director tick.
    ///
    /// 1. Decay biome pressure.
    /// 2. Check faction balance for snowball risk.
    /// 3. Generate corrective world events if needed.
    pub fn tick(&mut self, zones: &mut [Zone]) -> Vec<WorldEvent> {
        // 1. Decay biome pressure toward zero.
        for pressure in self.biome_pressure_map.values_mut() {
            *pressure = (*pressure * 0.98).max(0.0);
        }

        // 2. Apply zone pressure from combat / resource extraction.
        for zone in zones.iter() {
            let p = self.biome_pressure_map.entry(zone.id.clone()).or_insert(0.0);
            if matches!(zone.state, ZoneState::Contested { .. }) {
                *p = (*p + 0.01).min(1.0);
            }
        }

        // 3. Check for dominant faction (snowball prevention).
        let mut events = Vec::new();
        if let Some((dominant, &score)) = self.faction_balance.iter().max_by(|a, b| a.1.partial_cmp(b.1).unwrap_or(std::cmp::Ordering::Equal)) {
            if score > 0.75 {
                events.push(WorldEvent::SnowballCorrectionEvent {
                    dominant_faction: dominant.clone(),
                    correction_type:  CorrectionType::ResourceScarcity,
                });
            }
        }

        // 4. Trigger biome evolution for high-pressure zones.
        for (zone_id, &pressure) in &self.biome_pressure_map {
            if pressure > 0.8 {
                events.push(WorldEvent::BiomeEvolutionTrigger {
                    zone_id:       zone_id.clone(),
                    trigger_cause: BiomeEvolutionCause::CombatIntensity,
                });
            }
        }

        self.active_events.clone_from(&events);
        events
    }

    /// Apply economic pressure from a trade transaction.
    pub fn record_trade(&mut self, gold_value: u32) {
        // Large trades reduce economic stability slightly (inflation pressure).
        let impact = (gold_value as f32 / 10_000.0).min(0.01);
        self.economic_stability = (self.economic_stability - impact).max(0.0);
    }

    /// Recover economic stability over time (called each tick).
    pub fn recover_economy(&mut self) {
        self.economic_stability = (self.economic_stability + 0.001).min(1.0);
    }

    /// Update faction balance from zone control data.
    pub fn update_balance(&mut self, zone_control: &BTreeMap<FactionId, u32>, total_zones: u32) {
        self.faction_balance.clear();
        for (faction, &zones) in zone_control {
            self.faction_balance.insert(
                faction.clone(),
                zones as f32 / total_zones.max(1) as f32,
            );
        }
    }
}

// ─── WorldEvent ──────────────────────────────────────────────────────────────

/// A world event generated by the director.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WorldEvent {
    /// Dominant faction receives a corrective handicap.
    SnowballCorrectionEvent {
        dominant_faction: FactionId,
        correction_type:  CorrectionType,
    },
    /// A zone's biome begins evolving due to pressure.
    BiomeEvolutionTrigger {
        zone_id:       ZoneId,
        trigger_cause: BiomeEvolutionCause,
    },
    /// Global loot scarcity event (counters economy exploit).
    LootScarcityEvent { severity: f32 },
    /// Random world event (disaster, bonus, migration).
    NarrativeEvent { title: String, description: String },
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CorrectionType {
    ResourceScarcity,
    IncreasedContestRate,
    AiReinforcement,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BiomeEvolutionCause {
    CombatIntensity,
    EconomyImbalance,
    AiAdaptation,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn director_triggers_snowball_correction() {
        let mut dir = WorldDirector::new();
        dir.faction_balance.insert("synthesis".into(), 0.9);
        let events = dir.tick(&mut []);
        let has_correction = events.iter().any(|e| matches!(e, WorldEvent::SnowballCorrectionEvent { .. }));
        assert!(has_correction, "should trigger correction for dominant faction");
    }

    #[test]
    fn director_biome_evolution_for_high_pressure() {
        let mut dir = WorldDirector::new();
        dir.biome_pressure_map.insert("zone-A3".into(), 0.85);
        let events = dir.tick(&mut []);
        let has_biome = events.iter().any(|e| matches!(e, WorldEvent::BiomeEvolutionTrigger { .. }));
        assert!(has_biome);
    }

    #[test]
    fn economic_stability_recovers() {
        let mut dir = WorldDirector::new();
        dir.economic_stability = 0.5;
        dir.recover_economy();
        assert!(dir.economic_stability > 0.5);
    }
}
